// Client-side incident report export (CSV / PDF) — no backend involved yet,
// matches the rest of this app's "mock data + pure functions" pattern. Pulls
// straight from an `incidents.js` incident object (title, meta, storyline).
// Proves the "우리는 사건을 재구성한다" story: one incident in, one shareable
// file out.

import { jsPDF } from "jspdf";
import { DISPLAY_TIMEZONE } from "./timezone";

function csvEscape(value) {
  const str = String(value ?? "");
  if (/[",\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// One row per storyline entry, incident-level fields repeated on each row so
// the file stays a single flat table (opens cleanly in Excel/Sheets).
export function exportIncidentCSV(incident) {
  const headers = [
    "incident_id",
    "title",
    "severity",
    "status",
    "correlation_rule",
    "mitre_path",
    "target",
    "source_ip",
    "source_country",
    "first_detected",
    "event_offset",
    "event_source",
    "event_title",
    "event_detail",
    "event_mitre",
  ];

  const baseFields = [
    incident.id,
    incident.title,
    incident.severity,
    incident.status,
    incident.correlationRule,
    incident.mitrePath.join(" -> "),
    incident.target,
    incident.sourceIp,
    incident.sourceCountry,
    incident.firstDetected,
  ];

  const rows = incident.storyline.map((entry) => [
    ...baseFields,
    entry.offset,
    entry.source,
    entry.title,
    entry.detail.replace(/\n/g, " / "),
    entry.mitre,
  ]);

  const csv = [headers, ...rows].map((row) => row.map(csvEscape).join(",")).join("\r\n");
  // BOM so Excel on Windows/macOS opens 한글 as UTF-8 instead of mangling it.
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
  downloadBlob(`${incident.id}-report.csv`, blob);
}

const PAGE_MARGIN = 15;
const PAGE_WIDTH = 210; // A4 portrait, mm
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;

export function exportIncidentPDF(incident) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = PAGE_MARGIN;

  function ensureSpace(neededMm) {
    if (y + neededMm > PAGE_HEIGHT - PAGE_MARGIN) {
      doc.addPage();
      y = PAGE_MARGIN;
    }
  }

  function writeLines(lines, { size = 10, lineHeight = 5, color = [40, 40, 40] } = {}) {
    doc.setFontSize(size);
    doc.setTextColor(...color);
    lines.forEach((line) => {
      ensureSpace(lineHeight);
      doc.text(line, PAGE_MARGIN, y);
      y += lineHeight;
    });
  }

  // Header
  doc.setFontSize(16);
  doc.setTextColor(20, 20, 20);
  doc.text(`Incident Report - ${incident.id}`, PAGE_MARGIN, y);
  y += 8;
  writeLines(doc.splitTextToSize(incident.title, CONTENT_WIDTH), { size: 12, lineHeight: 6 });
  y += 2;

  writeLines(
    [
      `Severity: ${incident.severity}   Status: ${incident.status}`,
      `Target: ${incident.target}`,
      `Source: ${incident.sourceIp} (${incident.sourceCountry})`,
      `First Detected: ${incident.firstDetected}`,
      `Correlation Rule: ${incident.correlationRule}`,
      `MITRE Path: ${incident.mitrePath.join(" -> ")}`,
      `Risk Note: ${incident.riskNote}`,
    ],
    { size: 10, lineHeight: 5.5 }
  );

  y += 3;
  ensureSpace(10);
  doc.setDrawColor(200, 200, 200);
  doc.line(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN, y);
  y += 8;

  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Attack Storyline (WAS / Falco / K8s Audit)", PAGE_MARGIN, y);
  y += 8;

  incident.storyline.forEach((entry, i) => {
    ensureSpace(12);
    doc.setFontSize(11);
    doc.setTextColor(20, 20, 20);
    doc.text(`${entry.offset}  ·  ${entry.source}  ·  ${entry.title}  (${entry.mitre})`, PAGE_MARGIN, y);
    y += 6;

    const detailLines = doc.splitTextToSize(entry.detail.replace(/\n/g, "  |  "), CONTENT_WIDTH - 5);
    doc.setFontSize(9.5);
    doc.setTextColor(90, 90, 90);
    detailLines.forEach((line) => {
      ensureSpace(5);
      doc.text(line, PAGE_MARGIN + 5, y);
      y += 5;
    });
    y += i === incident.storyline.length - 1 ? 0 : 4;
  });

  y += 10;
  ensureSpace(6);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by SENTINEL-OPS · ${new Date().toLocaleString("ko-KR", { timeZone: DISPLAY_TIMEZONE })}`, PAGE_MARGIN, y);

  doc.save(`${incident.id}-report.pdf`);
}
