-- report_notification_connections CRUD가 감사 로그에 남길 행위 종류 추가.
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'REPORT_INTEGRATION_CONNECTED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'REPORT_INTEGRATION_UPDATED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'REPORT_INTEGRATION_DISCONNECTED';
